export const testField = [
  [{
    'bombsNearby': 0,
    'flag': false,
    'open': false,
    'withBomb': false,
    'x': 0,
    'y': 0
  }, {
    'bombsNearby': 0,
    'flag': false,
    'open': false,
    'withBomb': false,
    'x': 1,
    'y': 0
  }, {
    'bombsNearby': 1,
    'flag': false,
    'open': false,
    'withBomb': false,
    'x': 2,
    'y': 0
  }, {
    'bombsNearby': 1,
    'flag': false,
    'open': false,
    'withBomb': true,
    'x': 3,
    'y': 0
  }, {
    'bombsNearby': 1,
    'flag': false,
    'open': false,
    'withBomb': true,
    'x': 4,
    'y': 0
  }],
  [{
    'bombsNearby': 1,
    'flag': false,
    'open': false,
    'withBomb': false,
    'x': 0,
    'y': 1
  }, {
    'bombsNearby': 2,
    'flag': false,
    'open': false,
    'withBomb': false,
    'x': 1,
    'y': 1
  }, {
    'bombsNearby': 3,
    'flag': false,
    'open': false,
    'withBomb': false,
    'x': 2,
    'y': 1
  }, {
    'bombsNearby': 3,
    'flag': false,
    'open': false,
    'withBomb': false,
    'x': 3,
    'y': 1
  }, {
    'bombsNearby': 2,
    'flag': false,
    'open': false,
    'withBomb': false,
    'x': 4,
    'y': 1
  }],
  [{
    'bombsNearby': 1,
    'flag': false,
    'open': false,
    'withBomb': false,
    'x': 0,
    'y': 2
  }, {
    'bombsNearby': 1,
    'flag': false,
    'open': false,
    'withBomb': true,
    'x': 1,
    'y': 2
  }, {
    'bombsNearby': 1,
    'flag': false,
    'open': false,
    'withBomb': true,
    'x': 2,
    'y': 2
  }, {
    'bombsNearby': 2,
    'flag': false,
    'open': false,
    'withBomb': false,
    'x': 3,
    'y': 2
  }, {
    'bombsNearby': 1,
    'flag': false,
    'open': false,
    'withBomb': false,
    'x': 4,
    'y': 2
  }],
  [{
    'bombsNearby': 2,
    'flag': false,
    'open': false,
    'withBomb': false,
    'x': 0,
    'y': 3
  }, {
    'bombsNearby': 3,
    'flag': false,
    'open': false,
    'withBomb': false,
    'x': 1,
    'y': 3
  }, {
    'bombsNearby': 2,
    'flag': false,
    'open': false,
    'withBomb': false,
    'x': 2,
    'y': 3
  }, {
    'bombsNearby': 2,
    'flag': false,
    'open': false,
    'withBomb': false,
    'x': 3,
    'y': 3
  }, {
    'bombsNearby': 0,
    'flag': false,
    'open': false,
    'withBomb': true,
    'x': 4,
    'y': 3
  }],
  [{
    'bombsNearby': 0,
    'flag': false,
    'open': false,
    'withBomb': true,
    'x': 0,
    'y': 4
  }, {
    'bombsNearby': 1,
    'flag': false,
    'open': false,
    'withBomb': false,
    'x': 1,
    'y': 4
  }, {
    'bombsNearby': 0,
    'flag': false,
    'open': false,
    'withBomb': false,
    'x': 2,
    'y': 4
  }, {
    'bombsNearby': 1,
    'flag': false,
    'open': false,
    'withBomb': false,
    'x': 3,
    'y': 4
  }, {
    'bombsNearby': 1,
    'flag': false,
    'open': false,
    'withBomb': false,
    'x': 4,
    'y': 4
  }],
];
